import Head from "next/head";
import Landing from "../src/landing/Landing";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";


export default function Home() {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>{t("indexTitle")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />

    </>
  );
}
export async function getServerSideProps({ locale }) {
  return {
    props: {
      // // ...(await serverSideTranslations(locale, ["transliation"]))
      ...(await serverSideTranslations(locale, ["common"], null, ["en", "fa"])),
      // Will be passed to the page component as props
      locale,
    },
  };
}
